development:
  adapter: postgresql
  encoding: unicode
  database: GPXtra_development
  pool: 5
  username: pln
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: GPXtra_test
  pool: 5
  username: pln
  password:
